### ISSUE TITLE
Iterating through pages?

### ISSUE THREAD

**Issue by adiutores** [ioces/toshling#8]
`client.entries.list(account=...)` provides one page.

How is one supposed to iterate through all of the indicated data? This seems to be something that the client library should provide for, but I'm not finding an indication of how to do it.

**Comment by m-schubert** [comment]
I don't have a Toshl account any longer to test this, but I'd suggest providing a `page` argument.

**Comment by adiutores** [comment]
I've seen APIs provide an `iterate()` option, which I've included in https://github.com/ioces/toshling/pull/9 . It just makes life more convenient for the user :-)

**Comment by m-schubert** [comment]
Closed by #9.
